# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build and Publish
  displayName: Build and Publish image
  jobs:
  - job: BuildandPublish
    displayName: Build and Publish
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Team3ACRConnection'
        repository: 'T3-GetToWork'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
